#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash tools/parsespcl.sh [OPTIONS] SKILL_DIR [SKILL_DIR ...]

Pipeline:
  1) Copy source skills to working directory
  2) Convert each SKILL.md to <skill>.spcl via LLM (or mock mode)
  3) Merge generated .spcl using cclq and output a normalized combo bundle

Options:
  --source-dir DIR      Source skills directory. Default: .claude/skills
  --work-dir DIR        Working skills directory. Default: ./skills
  --out-dir DIR         Bundle output root. Default: ./trick
  --refresh-copy        Re-copy source directory into work dir before run
  --mock-llm            Skip API call and generate deterministic mock .spcl
  -h, --help            Show help

Examples:
  bash tools/parsespcl.sh skill1dir
  bash tools/parsespcl.sh skill1dir skill2dir
  bash tools/parsespcl.sh --source-dir /path/to/.claude/skills --refresh-copy skill1dir
EOF
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing command: $1" >&2
    exit 1
  }
}

source_dir=".claude/skills"
work_dir="./skills"
out_root="./trick"
refresh_copy=0
mock_llm=0

skills=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-dir)
      source_dir="${2:?missing value for --source-dir}"
      shift 2
      ;;
    --work-dir)
      work_dir="${2:?missing value for --work-dir}"
      shift 2
      ;;
    --out-dir)
      out_root="${2:?missing value for --out-dir}"
      shift 2
      ;;
    --refresh-copy)
      refresh_copy=1
      shift
      ;;
    --mock-llm)
      mock_llm=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --*)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      skills+=("$1")
      shift
      ;;
  esac
done

if [[ "${#skills[@]}" -eq 0 ]]; then
  echo "At least one SKILL_DIR is required." >&2
  usage >&2
  exit 1
fi

need_cmd bash
need_cmd sort

if [[ ! -x "./build/bin/cclq" ]]; then
  need_cmd make
  make all >/dev/null
fi

if [[ ! -d "$source_dir" ]]; then
  echo "Source skills directory not found: $source_dir" >&2
  exit 1
fi

if [[ -f "$work_dir" ]]; then
  echo "Work dir path is a file: $work_dir" >&2
  exit 1
fi

if [[ "$refresh_copy" -eq 1 && -d "$work_dir" ]]; then
  rm -rf "$work_dir"
fi

if [[ ! -d "$work_dir" ]]; then
  mkdir -p "$(dirname "$work_dir")"
  cp -R "$source_dir" "$work_dir"
fi

mkdir -p "$out_root"
combo_name="$(printf '%s-and-then-' "${skills[@]}")"
combo_name="${combo_name%-and-then-}"
bundle_dir="$out_root/$combo_name"
mkdir -p "$bundle_dir/spcl" "$bundle_dir/skills"

spcl_files=()
for skill in "${skills[@]}"; do
  skill_md="$work_dir/$skill/SKILL.md"
  if [[ ! -f "$skill_md" ]]; then
    echo "SKILL.md not found in work dir: $skill_md" >&2
    exit 1
  fi
  out_spcl="$bundle_dir/spcl/${skill}.spcl"
  if [[ "$mock_llm" -eq 1 ]]; then
    cat >"$out_spcl" <<EOF
meta =
  name = $skill
  version = 1

skill =
  name = $skill
  title = $skill
  description =
    generated by mock mode
EOF
    echo "Mock generated: $out_spcl"
  else
    bash tools/llskill2spcl.sh --skill "$skill_md" --out "$out_spcl"
  fi
  spcl_files+=("$out_spcl")

  if [[ -d "$work_dir/$skill" ]]; then
    cp -R "$work_dir/$skill" "$bundle_dir/skills/"
  fi
done

"./build/bin/cclq" "${spcl_files[@]}" -- >"$bundle_dir/normalized.spcl"

cat >"$bundle_dir/manifest.spcl" <<EOF
meta =
  name = $combo_name
  version = 1

compose =
  op = and-then
  inputs =
$(for s in "${skills[@]}"; do printf '    = %s\n' "$s"; done)
  output = $combo_name

bundle =
  root = $bundle_dir
  normalized = normalized.spcl
EOF

echo "Bundle generated: $bundle_dir"
echo "  - manifest:   $bundle_dir/manifest.spcl"
echo "  - normalized: $bundle_dir/normalized.spcl"
